### ISSUE TITLE
Corrupt images in docs

### ISSUE THREAD

**Issue by ts-stevem** [assimp/assimp_qt_viewer#1]
Some images in `assimp_qt_viewer/assimp_qt_viewer/doc/Assimp_qt_viewer. Manual (en).odt` ([here](https://github.com/assimp/assimp_qt_viewer/blob/master/assimp_qt_viewer/doc/Assimp_qt_viewer.%20Manual%20(en).odt)) are corrupt

Image around section 1.2 with `Read Error`
<img width="480" alt="Screen Shot 2020-12-25 at 11 33 02" src="https://user-images.githubusercontent.com/72423314/103115233-2210b300-46a5-11eb-8710-1d980ce6944e.png">

Image around section 2.2:
<img width="480" alt="Screen Shot 2020-12-25 at 11 38 55" src="https://user-images.githubusercontent.com/72423314/103115503-1d003380-46a6-11eb-9f45-3b32ad8634cb.png">

Image around section 3.1:
<img width="480" alt="Screen Shot 2020-12-25 at 11 39 11" src="https://user-images.githubusercontent.com/72423314/103115514-2ee1d680-46a6-11eb-88c5-ade4ccac10f2.png">

Image around section 4.5:
<img width="480" alt="Screen Shot 2020-12-25 at 11 39 21" src="https://user-images.githubusercontent.com/72423314/103115527-428d3d00-46a6-11eb-9e0a-2f7f15227380.png">

Image 18:
<img width="480" alt="Screen Shot 2020-12-25 at 11 39 47" src="https://user-images.githubusercontent.com/72423314/103115536-50db5900-46a6-11eb-983a-ba66057719fa.png">

Other images OK e.g.
<img width="480" alt="Screen Shot 2020-12-25 at 11 33 15" src="https://user-images.githubusercontent.com/72423314/103115255-3e145480-46a5-11eb-8aff-54167cb5eb17.png">
<img width="480" alt="Screen Shot 2020-12-25 at 11 33 25" src="https://user-images.githubusercontent.com/72423314/103115282-57b59c00-46a5-11eb-88cc-f4a6512e955a.png">

**Comment by kimkulling** [comment]
Deprecated.
